### ISSUE TITLE
formal argument "save_as" matched by multiple actual arguments

### ISSUE THREAD

**Issue by arthurgailes** [dslc-io/tidytuesdayR#76]
Hello,

Thanks for your work on this package; it's extremely helpful.

The following code produces an errror:

```
tidytuesdayR::use_tidytemplate(save_as = 'analysis')
Error in use_template("tidytemplate.Rmd", save_as = name, data = list(call_date = today(),  : 
  formal argument "save_as" matched by multiple actual arguments
```

My confusion arises from the use_tidytemplate help doc, which states the ... parameter passes arguments to use_template.

Regards.

**Comment by thebioengineer** [comment]
yeah, sorry for the confusion. You can use the `name` arugment to set the name you want to save the template as. I will work on making this clearer.

Also, sorry for the delay in response!
