### ISSUE TITLE
Deal with old failing weeks

### ISSUE THREAD

**Issue by jonthegeek** [dslc-io/tidytuesdayR#90]
This fails:

``` r
tidytuesdayR::tt_load(2018, 7)
#> --- Compiling #TidyTuesday Information for 2018-05-14 ----
#> --- There is 1 file available ---
#> --- Starting Download ---
#> 
#>  Downloading file 1 of 1: `week7_starwars.csv`
#> Error in nchar(x, "width"): invalid multibyte string, element 1
```

<sup>Created on 2023-05-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

[That week](https://github.com/rfordatascience/tidytuesday/tree/master/data/2018/2018-05-14) doesn't have a README for whatever reason, which I think is the source of the issue.

We should harden tidytuesdayR to deal with issues over in the main repo. If it can still get the data, do at least that much, and probably inform the user about any other specific strangeness.

**Comment by jonthegeek** [comment]
Oh, huh, it isn't the lack of README; it's the data itself. Fixing!

Still worth dealing with!

**Comment by thebioengineer** [comment]
The issue you are seeing comes from the data seeming to get corrupted on the gh side - I had some tests reading this week originally and started failing. I submitted a ticket to gh since it should work and the csv appeared to generally be fine.

**Comment by jonthegeek** [comment]
When I download the csv, it still fails.... because that dataset is a mess. I think this was a different style, where we gave them very very messy data to play with. I really don't think it's a GH error.

I think mostly making it fail with an informative error would be the fix to close this ticket.
